INSERT INTO restaurent (id, name, address, city, restaurent_description) VALUES
(1, 'Paradise Biryani', 'Begumpet', 'Hyderabad', 'Famous for biryani'),
(2, 'Shah Ghouse', 'Tolichowki', 'Hyderabad', 'Authentic Hyderabadi food'),
(3, 'Bawarchi', 'RTC Cross Roads', 'Hyderabad', 'Classic biryani and kebabs'),
(4, 'Rayalaseema Ruchulu', 'Jubilee Hills', 'Hyderabad', 'Andhra-style spicy dishes'),
(5, 'Chutneys', 'Hitech City', 'Hyderabad', 'South Indian tiffins and chutneys'),
(6, 'Ulavacharu', 'Gachibowli', 'Hyderabad', 'Andhra cuisine specialists'),
(7, 'Adaa', 'Falaknuma Palace', 'Hyderabad', 'Luxury dining experience'),
(8, 'Exotica', 'Banjara Hills', 'Hyderabad', 'Rooftop dining with great ambiance'),
(9, 'Absolute Barbecues', 'Gachibowli', 'Hyderabad', 'Best for barbecue lovers'),
(10, 'Ohri''s Jiva', 'Necklace Road', 'Hyderabad', 'Multi-cuisine with great view'),
(11, 'Hotel Shadab', 'Charminar', 'Hyderabad', 'Old city biryani special'),
(12, 'Pista House', 'Charminar', 'Hyderabad', 'Famous haleem and sweets'),
(13, 'Santosh Dhaba', 'Abids', 'Hyderabad', 'Pure veg delicacies'),
(14, 'Cafe Bahar', 'Basheer Bagh', 'Hyderabad', 'Authentic biryani'),
(15, 'Tatva', 'Jubilee Hills', 'Hyderabad', 'Premium vegetarian dining'),
(16, 'Minerva Coffee Shop', 'Himayatnagar', 'Hyderabad', 'South Indian coffee and snacks'),
(17, 'Conçu', 'Jubilee Hills', 'Hyderabad', 'Designer desserts and bakes'),
(18, 'Glocal Junction', 'Kondapur', 'Hyderabad', 'Modern global fusion dishes'),
(19, 'Barbeque Nation', 'Madhapur', 'Hyderabad', 'Unlimited buffet for foodies'),
(20, 'Biryaniwala', 'Miyapur', 'Hyderabad', 'Affordable biryani options'),
(21, 'Mandil', 'Banjara Hills', 'Hyderabad', 'Arabic and Indian fusion'),
(22, 'Our Place', 'Banjara Hills', 'Hyderabad', 'Family-friendly multi-cuisine'),
(23, 'Dakshin', 'ITC Kakatiya', 'Hyderabad', 'Luxury South Indian dining'),
(24, 'Aish', 'The Park', 'Hyderabad', 'Hyderabadi royal cuisine'),
(25, 'Biryani House', 'Kukatpally', 'Hyderabad', 'Affordable tasty biryani'),
(26, 'Green Park', 'Begumpet', 'Hyderabad', 'Buffet specialists'),
(27, 'Mainland China', 'Begumpet', 'Hyderabad', 'Authentic Chinese dining'),
(28, 'Sahib''s Barbeque', 'Hitech City', 'Hyderabad', 'Mughlai and BBQ combos'),
(29, 'Urban Asia', 'Banjara Hills', 'Hyderabad', 'Asian fusion dishes'),
(30, 'Over The Moon', 'Jubilee Hills', 'Hyderabad', 'Rooftop bar and restaurant'),
(31, 'Amara', 'Trident Hotel', 'Hyderabad', 'Fine dining buffet'),
(32, 'Flechazo', 'Gachibowli', 'Hyderabad', 'Mediterranean and Indian mix'),
(33, 'Water Front', 'Necklace Road', 'Hyderabad', 'Great view with good food'),
(34, 'Olive Bistro', 'Gandipet', 'Hyderabad', 'European fine dining'),
(35, 'Jewel of Nizam', 'Golkonda', 'Hyderabad', 'Royal Hyderabadi experience'),
(36, 'Sarvi', 'Banjara Hills', 'Hyderabad', 'Traditional biryani spot'),
(37, 'Karachi Bakery Cafe', 'Banjara Hills', 'Hyderabad', 'Snacks and bakery items'),
(38, 'Seasonal Tastes', 'Westin', 'Hyderabad', 'Luxury buffet and dining'),
(39, 'Little Italy', 'Jubilee Hills', 'Hyderabad', 'Pure veg Italian dining'),
(40, 'Zafran Exotica', 'Gachibowli', 'Hyderabad', 'Arabic and Mughlai combo'),
(41, 'Grand Hotel', 'Abids', 'Hyderabad', 'Old-school biryani joint'),
(42, 'Simply South', 'Film Nagar', 'Hyderabad', 'Authentic South Indian food'),
(43, 'Gufaa Ohri''s', 'Basheer Bagh', 'Hyderabad', 'Cave-themed restaurant'),
(44, 'Red Rhino', 'Gachibowli', 'Hyderabad', 'Microbrewery and restaurant'),
(45, 'China Bistro', 'Gachibowli', 'Hyderabad', 'Pan-Asian dining experience'),
(46, 'The Fisherman''s Wharf', 'Financial District', 'Hyderabad', 'Coastal seafood dishes'),
(47, 'Farzi Cafe', 'Jubilee Hills', 'Hyderabad', 'Modern Indian fusion'),
(48, 'The Glass Onion', 'Financial District', 'Hyderabad', 'Trendy fine dining'),
(49, 'The Hoppery', 'Gandipet', 'Hyderabad', 'Craft beers and bites'),
(50, 'Autumn Leaf Cafe', 'Jubilee Hills', 'Hyderabad', 'Outdoor bohemian vibe');
